### ISSUE TITLE
Scanner is listed in GitHub Marketplace

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/dx-scanner#175]
As a user I want to have an easy installation of DX Scanner on Github from its marketplace.

**TODO:**

- [x] report as a comment on a pull request (editing next time) @prokopsimek 

- [ ] (optional) report DX Score from repositories to remote db @prokopsimek 

- [ ] (optional) error logs @prokopsimek 

- [x] fill mktplc details @adelkahomolova 

- [x] prepare mktplc description @adelkahomolova 

- [x] create GitHub Action for CI run on pull requests @adelkahomolova & @prokopsimek 

- [x] register to mktplc @prokopsimek

**Comment by prokopsimek** [comment]
Link to feature: https://dxheroes.productboard.com/feature-board/planning/features/3310038

**Comment by prokopsimek** [comment]
related to #111
